import { Icon } from '../components/Icon';
import { routes, site } from '../site';
import { Callout, DataTable, LegalLayout, type LegalSection } from './LegalLayout';

const mail = (addr: string) => <a href={`mailto:${addr}`}>{addr}</a>;

const sections: LegalSection[] = [
  {
    id: 'who',
    title: 'Who we are',
    body: (
      <>
        <p>
          {site.name} (“the app”, “we”, “us”) is published by {site.legalName}, {site.address}. We are the controller
          of the personal information described in this policy.
        </p>
        <p>
          This policy covers the {site.name} apps for iPhone and Android and this website. Questions about it go to{' '}
          {mail(site.privacyEmail)}.
        </p>
      </>
    ),
  },
  {
    id: 'collect',
    title: 'What we collect',
    body: (
      <>
        <p>We only collect what the app needs to work for you and your partner.</p>
        <DataTable
          head={['Category', 'What it includes', 'Where it comes from']}
          rows={[
            [
              'Account',
              'Email address, password (stored only as a secure hash), display name and optional profile photo.',
              'You, when you sign up or edit your profile.',
            ],
            [
              'Your hub',
              'Which hub you belong to, who your partner is, the invite code, and the date you got together.',
              'You and your partner.',
            ],
            [
              'Check-ins',
              'Your daily mood, social battery, streak, and which nudges you marked as sent.',
              'You.',
            ],
            [
              'Shared content',
              'Calendar events and reminders, bucket list items, gallery photos, the details wiki, love languages, goals, and game data (coin flips, wheel options, trivia questions and answers, date ideas, movie swipes).',
              'You and your partner.',
            ],
            [
              'Private content',
              'Your to-dos, your coach conversations and any files you attach to them.',
              'You.',
            ],
            [
              'Notifications',
              'A push notification token for your device, your notification preferences, and your in-app notification history.',
              'Your device, with your permission.',
            ],
            [
              'Usage counters',
              'How many coach questions you asked today and how many ad rewards you claimed.',
              'Generated by the app.',
            ],
            [
              'Advertising data (free accounts only)',
              'Your device’s advertising ID (where permitted), IP address, device and app information, ad interactions, and your consent choices.',
              'Collected by Google’s ad SDK in the app. See section 7.',
            ],
            [
              'Technical logs',
              'IP address, device type, operating system, app version, timestamps and error information.',
              'Recorded automatically by our hosting providers for security and reliability.',
            ],
          ]}
        />
        <Callout tone="amber" title="Sensitive details are optional">
          The details wiki has fields for things like allergies or blood group. Filling them in is entirely up to you.
          If you do, that information is shared with your partner, and we use it only to show it to the two of you.
        </Callout>
        <p>
          <b>What we don’t collect:</b> your precise location, your contacts, or your payment card details. When the
          nudge sheet opens WhatsApp, Instagram or another app, it just opens that app. We don’t read anything from
          it.
        </p>
      </>
    ),
  },
  {
    id: 'use',
    title: 'How we use it',
    body: (
      <>
        <DataTable
          head={['Purpose', 'Details', 'Legal basis (UK/EEA)']}
          rows={[
            [
              'Run the app',
              'Create your account, connect you to your partner, store and sync what you add, and keep your streak.',
              'Performing our contract with you.',
            ],
            [
              'Notify you',
              'Tell you when your partner checks in, finishes a game or adds something.',
              'Performing our contract. Push notifications also need your device permission.',
            ],
            [
              'Coach replies',
              'Send your coach messages to our AI provider to generate a response.',
              'Performing our contract, and your explicit consent for any sensitive details you choose to include.',
            ],
            [
              'Show ads',
              'Show banner ads and optional rewarded ads to people without Premium.',
              'Your consent for personalised ads. Legitimate interests for non-personalised ads, which fund the free app.',
            ],
            [
              'Keep things safe',
              'Prevent abuse and fraud, enforce limits, fix bugs and secure our systems.',
              'Legitimate interests.',
            ],
            [
              'Premium',
              'Check whether your account has an active subscription.',
              'Performing our contract.',
            ],
            [
              'Legal',
              'Meet tax, accounting and other legal obligations, and answer lawful requests.',
              'Legal obligation.',
            ],
          ]}
        />
        <p>
          We don’t use your content to build advertising profiles, and we don’t make decisions about you that have legal
          or similarly significant effects by automated means.
        </p>
      </>
    ),
  },
  {
    id: 'partner',
    title: 'What your partner can see',
    body: (
      <>
        <p>{site.name} is built for exactly two people, so a lot of it is shared by design.</p>
        <div className="split-cards">
          <div className="split-card shared">
            <strong>
              <Icon name="heart" size={16} /> Shared with your partner
            </strong>
            <ul>
              <li>Your name, profile photo and check-ins</li>
              <li>Calendar events and reminders</li>
              <li>Bucket list and gallery</li>
              <li>The details wiki, including what you write about each other</li>
              <li>Love languages, goals and game results</li>
              <li>Notifications about things you do in the hub</li>
            </ul>
          </div>
          <div className="split-card mine">
            <strong>
              <Icon name="lock" size={16} /> Only you
            </strong>
            <ul>
              <li>Your email address and password</li>
              <li>Your to-dos</li>
              <li>Your coach conversations and attachments</li>
              <li>Your notification settings</li>
            </ul>
          </div>
        </div>
        <p>
          These rules are enforced by access controls on our servers, not just hidden in the app. Please don’t add
          anything to the shared parts of the app that you wouldn’t want your partner to see.
        </p>
      </>
    ),
  },
  {
    id: 'sharing',
    title: 'Who we share it with',
    body: (
      <>
        <p>
          <b>We do not sell your personal information, and we never give your check-ins, photos, messages or coach
          chats to advertisers.</b>{' '}
          We share data only with service providers that help us run the app. They may use it only to provide their
          services to us.
        </p>
        <DataTable
          head={['Provider', 'What they do', 'Data involved']}
          rows={[
            [
              'Supabase',
              'Hosts our database, sign-in, file storage and server functions.',
              'All app data described above.',
            ],
            [
              'Google (Gemini API)',
              'Generates the coach’s replies.',
              'Your coach messages, the conversation so far, and any files you attach.',
            ],
            [
              'Google (AdMob)',
              'Serves ads to people without Premium and asks for consent where required.',
              'Advertising data described in section 2.',
            ],
            [
              'Expo, Apple and Google (Firebase Cloud Messaging)',
              'Deliver push notifications to your device.',
              'Your push token and the notification text.',
            ],
            [
              'The Movie Database (TMDB)',
              'Supplies the films in the movie picker.',
              'Only the genre and decade you choose, sent from our servers. Nothing that identifies you.',
            ],
            [
              'Apple App Store and Google Play',
              'Distribute the app and handle Premium payments.',
              'Their own records of your purchase. We only receive whether a subscription is active.',
            ],
          ]}
        />
        <p>We may also disclose information:</p>
        <ul>
          <li>if the law requires it, or to respond to a valid legal request;</li>
          <li>to protect the safety, rights or property of our users, the public or us;</li>
          <li>
            as part of a merger, acquisition or sale of assets. We would tell you before your information became subject
            to a different privacy policy.
          </li>
        </ul>
        <p>
          <b>California residents:</b> we don’t sell personal information for money. Showing ads through Google may
          count as “sharing” for cross-context behavioural advertising under California law. You can opt out as
          described in section 7, or by upgrading to Premium.
        </p>
      </>
    ),
  },
  {
    id: 'coach',
    title: 'The AI coach',
    body: (
      <>
        <p>
          When you ask the coach something, our server sends your message, the earlier messages in that conversation
          and any attachments to Google’s Gemini API. Google uses them to write the reply, under its API terms. We don’t
          send your partner’s data unless you include it in what you write.
        </p>
        <p>
          Coach conversations are stored so you can come back to them. They are private to you, and we don’t read them
          except where needed to investigate abuse or a problem you report to us.
        </p>
        <Callout tone="iris" title="Not a substitute for professional help">
          The coach offers general guidance and can make mistakes. If you or someone else is in danger, contact your
          local emergency services.
        </Callout>
      </>
    ),
  },
  {
    id: 'choices',
    title: 'Ads and your choices',
    body: (
      <>
        <p>
          Accounts without Premium see a small number of clearly labelled banner ads. You can also choose to watch a
          short ad for an extra coach question. That is always optional. Ads are served by Google AdMob. You can read
          how Google uses this information at{' '}
          <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener">
            policies.google.com/technologies/partner-sites
          </a>
          .
        </p>
        <ul>
          <li>
            <b>UK, EEA and Switzerland:</b> we ask for your consent before showing personalised ads. You can change your
            choice at any time from the privacy options in the app’s settings.
          </li>
          <li>
            <b>iPhone:</b> we only use your advertising identifier if you allow tracking when iOS asks. You can change
            this in Settings → Privacy &amp; Security → Tracking.
          </li>
          <li>
            <b>Android:</b> you can reset or delete your advertising ID in your device’s Settings → Google (or Privacy)
            → Ads.
          </li>
          <li>
            <b>Everyone:</b> Premium removes ads completely. If you decline personalised ads you may still see
            non-personalised ones, which are based on the app itself rather than on you.
          </li>
        </ul>
        <p>
          You can turn push notifications off at any time in your device settings or in the app’s notification
          settings.
        </p>
      </>
    ),
  },
  {
    id: 'retention',
    title: 'How long we keep it',
    body: (
      <ul>
        <li>We keep your account and content for as long as your account is active.</li>
        <li>
          Deleting an item in the app removes it from our live systems. Deleting your account removes your personal
          data within 30 days, as described on the <a href={routes.deleteAccount}>account deletion page</a>.
        </li>
        <li>
          Encrypted backups are kept for up to 30 days, so deleted data can remain in backups for that long before it
          is overwritten.
        </li>
        <li>Push tokens are removed when you sign out or when the device stops accepting notifications.</li>
        <li>Daily usage counters are only used for that day’s limits.</li>
        <li>We keep anything the law requires us to keep, such as financial records, for as long as the law requires.</li>
      </ul>
    ),
  },
  {
    id: 'security',
    title: 'Security',
    body: (
      <p>
        Data is encrypted in transit, and shared data is only readable by members of the hub it belongs to. Server
        keys never ship inside the app, and access to production systems is restricted. No system is perfectly
        secure, so please use a strong, unique password. If we become aware of a breach that affects you, we will tell
        you and the relevant authorities as the law requires.
      </p>
    ),
  },
  {
    id: 'transfers',
    title: 'International transfers',
    body: (
      <p>
        Our main servers are in {site.dataRegion}. Some providers, including Google and Expo, may process data in other
        countries, including the United States. Where UK or EEA data is transferred to a country without an adequacy
        decision, we rely on safeguards such as the European Commission’s Standard Contractual Clauses and the UK
        Addendum.
      </p>
    ),
  },
  {
    id: 'rights',
    title: 'Your rights',
    body: (
      <>
        <p>Depending on where you live, you may have the right to:</p>
        <ul>
          <li>get a copy of your personal information, including in a portable format;</li>
          <li>correct information that is wrong;</li>
          <li>have your information deleted;</li>
          <li>object to, or ask us to limit, certain uses;</li>
          <li>withdraw consent at any time, without affecting what happened before;</li>
          <li>not be treated differently for exercising these rights;</li>
          <li>complain to your data protection authority, such as the ICO in the UK or your local EU authority.</li>
        </ul>
        <p>
          To use any of these rights, email {mail(site.privacyEmail)} from the address on your account. We’ll confirm
          it’s you before acting, and reply within one month (45 days for California requests). You can also correct or
          delete many things directly in the app.
        </p>
      </>
    ),
  },
  {
    id: 'children',
    title: 'Children',
    body: (
      <p>
        {site.name} is for adults aged {site.minimumAge} and over, and isn’t directed at children. We don’t knowingly
        collect information from anyone under {site.minimumAge}. If you think a child has created an account, contact{' '}
        {mail(site.privacyEmail)} and we’ll delete it.
      </p>
    ),
  },
  {
    id: 'cookies',
    title: 'This website and cookies',
    body: (
      <p>
        This website doesn’t use cookies, analytics or advertising trackers, and its fonts are served from our own
        domain. If you switch between light and dark themes, that choice is saved in your browser’s local storage and
        never sent to us. Our hosting provider keeps standard server logs, such as IP address and pages requested, for
        security.
      </p>
    ),
  },
  {
    id: 'changes',
    title: 'Changes to this policy',
    body: (
      <p>
        We’ll update this page when our practices change and change the date at the top. If a change is significant,
        we’ll also tell you in the app or by email before it takes effect.
      </p>
    ),
  },
  {
    id: 'contact',
    title: 'Contact us',
    body: (
      <p>
        {site.legalName}
        <br />
        {site.address}
        <br />
        Privacy questions: {mail(site.privacyEmail)}
        <br />
        Everything else: {mail(site.contactEmail)}
      </p>
    ),
  },
];

export default function Privacy() {
  return (
    <LegalLayout
      eyebrow="Privacy policy"
      title="Your hub is for two. Here’s how we look after it."
      intro={
        <p>
          Plain language first, detail below. If anything is unclear, email {mail(site.privacyEmail)}.
        </p>
      }
      sections={sections}
    >
      <div className="summary-cards">
        <div>
          <Icon name="shield" size={22} />
          <strong>We don’t sell what you write</strong>
          <span>Check-ins, photos, messages and coach chats are never shared with advertisers.</span>
        </div>
        <div>
          <Icon name="lock" size={22} />
          <strong>Private stays private</strong>
          <span>Your to-dos and coach chats are visible only to you, even to your partner.</span>
        </div>
        <div>
          <Icon name="eye" size={22} />
          <strong>You choose on ads</strong>
          <span>Consent controls in the app. Premium removes ads completely.</span>
        </div>
        <div>
          <Icon name="trash" size={22} />
          <strong>Leave any time</strong>
          <span>
            Delete your account and data. <a href={routes.deleteAccount}>Here’s how</a>.
          </span>
        </div>
      </div>
    </LegalLayout>
  );
}
